import Link from 'next/link'
import { AdminLayout } from '@/components/AdminLayout'
import { SettingKeyEditor } from '@/components/admin/SettingKeyEditor'
import { StatCard } from '@/components/admin/StatCard'
import { SubsectionNav } from '@/components/admin/SubsectionNav'
import { adminMarketingSubsections } from '@/components/admin/subsections'
import { prisma } from '@/lib/prisma'
import { getLoyaltyProgramConfig } from '@/lib/actions/rewards'

export default async function AdminMarketingLoyaltyPage() {
  const [config, configRow, rewardCoupons] = await Promise.all([
    getLoyaltyProgramConfig(),
    prisma.siteSettings.findUnique({ where: { key: 'loyaltyProgramConfig' } }),
    prisma.coupon.findMany({
      where: {
        code: {
          startsWith: 'LOYAL-',
        },
      },
      orderBy: { createdAt: 'desc' },
      take: 20,
    }),
  ])

  const configValue = configRow?.value ?? JSON.stringify(config, null, 2)

  return (
    <AdminLayout title="Loyalty Program" subtitle="Control buyer rewards policy and reward-coupon output">
      <SubsectionNav items={adminMarketingSubsections} />

      <div className="grid gap-4 md:grid-cols-4">
        <StatCard label="Reward Coupons" value={String(rewardCoupons.length)} hint="Generated by buyer claims" />
        <StatCard label="Active Reward Coupons" value={String(rewardCoupons.filter((coupon) => coupon.isActive && (coupon.maxUses == null || coupon.usedCount < coupon.maxUses)).length)} hint="Still available to use" />
        <StatCard label="Reward Coupon Uses" value={String(rewardCoupons.reduce((sum, coupon) => sum + coupon.usedCount, 0))} hint="Completed redemptions" />
        <StatCard label="Points Per $1" value={String(config.pointsPerCurrencyUnit)} hint="Current earning rate" />
      </div>

      <div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]">
        <SettingKeyEditor
          settingKey="loyaltyProgramConfig"
          label="Loyalty Program Config"
          description="JSON config for points accrual, tier thresholds, and claimable reward coupon rules."
          multiline
          initialValue={configValue}
        />

        <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
          <div className="flex items-center justify-between gap-3">
            <div>
              <h3 className="text-sm font-bold uppercase tracking-[0.08em] text-slate-800">Current Policy</h3>
              <p className="mt-1 text-xs text-slate-500">Live summary of the loyalty rules buyers are using now.</p>
            </div>
            <Link href="/dashboard/rewards" className="text-xs font-semibold text-blue-600 hover:underline">
              Open Buyer View
            </Link>
          </div>
          <div className="mt-4 space-y-3 text-sm text-slate-700">
            <div className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3">
              Buyers earn <span className="font-semibold">{config.pointsPerCurrencyUnit}</span> points per $1 of delivered order value.
            </div>
            <div className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3">
              Reward claim cost: <span className="font-semibold">{config.rewardCouponPointsCost}</span> points for a <span className="font-semibold">${config.rewardCouponDiscount.toFixed(2)}</span> coupon.
            </div>
            <div className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3">
              Coupon minimum order: <span className="font-semibold">${config.rewardCouponMinOrder.toFixed(2)}</span>. Expiry window: <span className="font-semibold">{config.rewardCouponExpiryDays}</span> days.
            </div>
            <div className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3">
              Tier thresholds: <span className="font-semibold">{config.tierThresholds.map((entry) => `${entry.tier} ${entry.minPoints}+`).join(' | ')}</span>
            </div>
          </div>
        </article>
      </div>

      <div className="mt-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-bold uppercase tracking-[0.08em] text-slate-800">Recent Reward Coupons</h3>
          <Link href="/admin/coupons" className="text-xs font-semibold text-blue-600 hover:underline">
            Open Coupons
          </Link>
        </div>
        <div className="mt-3 overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs uppercase tracking-[0.08em] text-slate-500">
                <th className="pb-2">Code</th>
                <th className="pb-2">Discount</th>
                <th className="pb-2">Usage</th>
                <th className="pb-2">Expires</th>
                <th className="pb-2">Status</th>
              </tr>
            </thead>
            <tbody>
              {rewardCoupons.map((coupon) => (
                <tr key={coupon.id} className="border-t border-slate-100">
                  <td className="py-2 font-mono text-xs text-slate-700">{coupon.code}</td>
                  <td className="py-2 text-slate-700">{coupon.isPercent ? `${coupon.discount}%` : `$${coupon.discount}`}</td>
                  <td className="py-2 text-slate-600">{coupon.usedCount}/{coupon.maxUses ?? 'unlimited'}</td>
                  <td className="py-2 text-slate-600">{coupon.expiresAt ? new Date(coupon.expiresAt).toLocaleDateString() : '-'}</td>
                  <td className="py-2">
                    <span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${coupon.isActive && (coupon.maxUses == null || coupon.usedCount < coupon.maxUses) ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>
                      {coupon.isActive && (coupon.maxUses == null || coupon.usedCount < coupon.maxUses) ? 'ACTIVE' : 'USED'}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {rewardCoupons.length === 0 && (
            <p className="pt-4 text-sm text-slate-500">No loyalty coupons have been claimed yet.</p>
          )}
        </div>
      </div>
    </AdminLayout>
  )
}
